//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserClient.OrderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderService.IOrderService")]
    public interface IOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/PlaceOrder", ReplyAction="http://tempuri.org/IOrderService/PlaceOrderResponse")]
        void PlaceOrder(string customerName, System.Collections.Generic.Dictionary<string, int> orderRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/PlaceOrder", ReplyAction="http://tempuri.org/IOrderService/PlaceOrderResponse")]
        System.Threading.Tasks.Task PlaceOrderAsync(string customerName, System.Collections.Generic.Dictionary<string, int> orderRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetCustomerOrders", ReplyAction="http://tempuri.org/IOrderService/GetCustomerOrdersResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, int>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] GetCustomerOrders(string customerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetCustomerOrders", ReplyAction="http://tempuri.org/IOrderService/GetCustomerOrdersResponse")]
        System.Threading.Tasks.Task<object[]> GetCustomerOrdersAsync(string customerName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderServiceChannel : UserClient.OrderService.IOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<UserClient.OrderService.IOrderService>, UserClient.OrderService.IOrderService {
        
        public OrderServiceClient() {
        }
        
        public OrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PlaceOrder(string customerName, System.Collections.Generic.Dictionary<string, int> orderRows) {
            base.Channel.PlaceOrder(customerName, orderRows);
        }
        
        public System.Threading.Tasks.Task PlaceOrderAsync(string customerName, System.Collections.Generic.Dictionary<string, int> orderRows) {
            return base.Channel.PlaceOrderAsync(customerName, orderRows);
        }
        
        public object[] GetCustomerOrders(string customerName) {
            return base.Channel.GetCustomerOrders(customerName);
        }
        
        public System.Threading.Tasks.Task<object[]> GetCustomerOrdersAsync(string customerName) {
            return base.Channel.GetCustomerOrdersAsync(customerName);
        }
    }
}
